{{- if .Values.b.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "hxy.b.fullname" . }}
  labels:
    {{- include "hxy.labels" . | nindent 4 }}
spec:
  {{- if not .Values.b.autoscaling.enabled }}
  replicas: {{ .Values.b.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "hxy.b.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.b.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "hxy.b.selectorLabels" . | nindent 8 }}
    spec:
      restartPolicy: Always
      {{- with .Values.b.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "hxy.b.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.b.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ include "hxy.b.name" $ }}
          securityContext:
            {{- toYaml .Values.b.securityContext | nindent 12 }}
          image: "{{ .Values.b.image.repository }}:{{ .Values.b.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.b.image.pullPolicy }}
          env:
            {{- range $key, $value := .Values.b.env }}
            - name: {{ $key }}
              valueFrom:
                configMapKeyRef:
                  name: {{ include "hxy.b.fullname" $ }}
                  key: {{ $key }}
            {{- end }}
            - name: DB_HOST
              value: {{ include "hxy.db.fullname" $ }}.{{ $.Release.Namespace }}
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.db.secretName }}
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.db.secretName }}
                  key: password
            - name: DATABASE_URL
              value: $(DB_DRIVER)://$(DB_USER):$(DB_PASSWORD)@$(DB_HOST):$(DB_PORT)/$(DB_NAME)?search_path=auth&sslmode=$(DB_SSL)
            - name: PGRST_JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.jwt.secretName }}
                  key: secret
          ports:
            - name: b
              containerPort: 8888
              protocol: TCP
          {{- with .Values.b.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.b.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.b.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.b.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.b.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        {{- if .Values.b.persistence.enabled }}
        - name: b-data
          persistentVolumeClaim:
            claimName: {{ include "hxy.b.fullname" . }}-pvc
        {{- end }}
        {{- with .Values.b.volumes }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
{{- end }}