{{- if .Values.db.enabled -}}
{{- if .Values.db.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "hxy.db.serviceAccountName" . }}
  labels:
    {{- include "hxy.labels" . | nindent 4 }}
  {{- with .Values.db.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}