{{- if .Values.db.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "hxy.db.fullname" . }}
  labels:
    {{- include "hxy.labels" . | nindent 4 }}
spec:
  type: {{ .Values.db.service.type }}
  ports:
    - port: {{ .Values.db.service.port }}
      targetPort: 5432
      protocol: TCP
      name: mysql
  selector:
    {{- include "hxy.db.selectorLabels" . | nindent 4 }}
{{- end }}