{{- if .Values.f.enabled -}}
{{- if .Values.f.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "hxy.f.serviceAccountName" . }}
  labels:
    {{- include "hxy.labels" . | nindent 4 }}
  {{- with .Values.f.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}