spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: res74984
    url: jdbc:postgresql://127.0.0.1:5432/ai_assistant_db
    type: com.alibaba.druid.pool.DruidDataSource
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password:  # 如果有密码，请填写
      database: 0  # 使用的数据库编号，默认是0
      timeout: 5000  # 连接超时时间（毫秒）
      lettuce:
        pool:
          max-active: 8  # 最大活动连接数
          max-wait: -1  # 获取连接的最大等待时间（毫秒），-1表示无限等待
          max-idle: 8  # 最大空闲连接数
          min-idle: 0  # 最小空闲连接数


#wx:
#  appId: wx7f269cb65f6eef7a
#  appSecret: e47bd03734db8f262b0a1c052f43e326
#  token: 123456
#  #项目部署服务ip+端口映射地址
#  domain: http://xh7hfq.natappfree.cc
#  #微信用户信息扫码回调地址
#  redirect-uri: /saveUserInfo
#  #微信回复模板ID
#  templateId: 6Zsp3pJJges0BvbFF81pPRX-3wcmAgMmW3vAp8I6koo

wx:
  appId: wx7f269cb65f6eef7a
  appSecret: e47bd03734db8f262b0a1c052f43e326
  token: 123456
  #项目部署服务ip+端口映射地址
  domain: http://jivk9p.natappfree.cc
  #微信用户信息扫码回调地址
  redirect-uri: /saveUserInfo
  #微信回复模板ID
  templateId: 6Zsp3pJJges0BvbFF81pPRX-3wcmAgMmW3vAp8I6koo

#这里配置腾讯云短信验证码发送参数
tengxun:
  secretId: AKID76yc4KQUSSNn4Pey73nJfojQt9FA00vx
  secretKey: BD9woQq5FBzafkeMtDLH5RdeR0MUQAh0
  sdkAppId: 1400874223
  signName: 魔音1号公众号
  templateId: 2288136

